apiVersion: 1

datasources:
  - name: LocAiOps Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: airflow
    user: locaiops
    secureJsonData:
      password: locaiops
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
